// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo7jysxXab3rVh1YiCCO-TKlW3nn5Qjl4',
    appId: '1:472655185580:web:aeee5a9c2c58c64d0d8109',
    messagingSenderId: '472655185580',
    projectId: 'todo-app-40ea0',
    authDomain: 'todo-app-40ea0.firebaseapp.com',
    storageBucket: 'todo-app-40ea0.firebasestorage.app',
    measurementId: 'G-KJ6S5K87GM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl0NzctqfQvry-dpXte-0JDES-ge-ZHCg',
    appId: '1:472655185580:android:0b454f8c6f4e25fd0d8109',
    messagingSenderId: '472655185580',
    projectId: 'todo-app-40ea0',
    storageBucket: 'todo-app-40ea0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7wAmQ7oWKEoSKQo39tsEGYD-5imVD-Sw',
    appId: '1:472655185580:ios:5848b7197be0d7b10d8109',
    messagingSenderId: '472655185580',
    projectId: 'todo-app-40ea0',
    storageBucket: 'todo-app-40ea0.firebasestorage.app',
    iosBundleId: 'com.example.chattApp',
  );
}
